### PR TITLE
chore: preparing 3.10.0 release.

### PR DESCRIPTION
**Pull request by msohailhussain**
## Summary
- prepare for release 3.9.0

### CODE REVIEW

**Review by dustin-sier — APPROVED** [review]
LGTM. Thanks!

**Comment by The-inside-man** [comment]
Should we include deprecation notes in the release notes ?

**Comment by msohailhussain** [comment]
> Should we include deprecation notes in the release notes ?

In the developer doc we have already mentioned there.

**Review by jaeopt — CHANGES_REQUESTED** [review]
Some OptimizelyConfig, etc has backticks and others not. Can be consistent.

**Review by jaeopt — APPROVED** [review]
LGTM

**Pull request merged**
