### PR TITLE
[FSSDK-10665] fix: Github Actions YAML files vulnerable to script injections corrected

### PR DESCRIPTION
**Pull request by FarhanAnjum-opti**
## Summary
Instead of directly using variables that can contain user input, new intermediate variables were introduced so that script injection attacks could be mitigated. Also removed unnecessary use of ${{ }} as using it makes the file vulnerable.

## Issues
- [FSSDK-10665](https://jira.sso.episerver.net/browse/FSSDK-10665)

### CODE REVIEW

**Review by mikechu-optimizely — APPROVED** [review]
LGTM. Thanks for reviewing the workflows.

**Comment by mikechu-optimizely** [comment]
@FarhanAnjum-opti  I'm researching the CI test error...

**Comment by muzahidul-opti** [comment]
Great to see your first PR being reviewed! I made a few small updates to the title and description.

**Comment by mikechu-optimizely** [comment]
@FarhanAnjum-opti  I finally fixed the problem with CI. You're welcome to squash+merge when you're ready.

**Pull request merged**
